In [2]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
data=pd.read_csv("framingham.csv")

In [4]:
data

male  age  education  currentSmoker  cigsPerDay  BPMeds  \
0        1   39        4.0              0         0.0     0.0   
1        0   46        2.0              0         0.0     0.0   
2        1   48        1.0              1        20.0     0.0   
3        0   61        3.0              1        30.0     0.0   
4        0   46        3.0              1        23.0     0.0   
...    ...  ...        ...            ...         ...     ...   
4233     1   50        1.0              1         1.0     0.0   
4234     1   51        3.0              1        43.0     0.0   
4235     0   48        2.0              1        20.0     NaN   
4236     0   44        1.0              1        15.0     0.0   
4237     0   52        2.0              0         0.0     0.0   

      prevalentStroke  prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  \
0                   0             0         0    195.0  106.0   70.0  26.97   
1                   0             0         0    250.0  121.0   81.0  28.73   
2                   0             0         0    245.0  127.5   80.0  25.34   
3                   0             1         0    225.0  150.0   95.0  28.58   
4                   0             0         0    285.0  130.0   84.0  23.10   
...               ...           ...       ...      ...    ...    ...    ...   
4233                0             1         0    313.0  179.0   92.0  25.97   
4234                0             0         0    207.0  126.5   80.0  19.71   
4235                0             0         0    248.0  131.0   72.0  22.00   
4236                0             0         0    210.0  126.5   87.0  19.16   
4237                0             0         0    269.0  133.5   83.0  21.47   

      heartRate  glucose  TenYearCHD  
0          80.0     77.0           0  
1          95.0     76.0           0  
2          75.0     70.0           0  
3          65.0    103.0           1  
4          85.0     85.0           0  
...         ...      ...         ...  
4233       66.0     86.0           1  
4234       65.0     68.0           0  
4235       84.0     86.0           0  
4236       86.0      NaN           0  
4237       80.0    107.0           0  

[4238 rows x 16 columns]

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4238 entries, 0 to 4237
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   male             4238 non-null   int64  
 1   age              4238 non-null   int64  
 2   education        4133 non-null   float64
 3   currentSmoker    4238 non-null   int64  
 4   cigsPerDay       4209 non-null   float64
 5   BPMeds           4185 non-null   float64
 6   prevalentStroke  4238 non-null   int64  
 7   prevalentHyp     4238 non-null   int64  
 8   diabetes         4238 non-null   int64  
 9   totChol          4188 non-null   float64
 10  sysBP            4238 non-null   float64
 11  diaBP            4238 non-null   float64
 12  BMI              4219 non-null   float64
 13  heartRate        4237 non-null   float64
 14  glucose          3850 non-null   float64
 15  TenYearCHD       4238 non-null   int64  
dtypes: float64(9), int64(7)
memory usage: 529.9 KB


In [6]:
data.isna().sum()

male                 0
age                  0
education          105
currentSmoker        0
cigsPerDay          29
BPMeds              53
prevalentStroke      0
prevalentHyp         0
diabetes             0
totChol             50
sysBP                0
diaBP                0
BMI                 19
heartRate            1
glucose            388
TenYearCHD           0
dtype: int64

In [7]:
data.dropna(inplace=True)

In [14]:
data.isna().sum()

male               0
age                0
education          0
currentSmoker      0
cigsPerDay         0
BPMeds             0
prevalentStroke    0
prevalentHyp       0
diabetes           0
totChol            0
sysBP              0
diaBP              0
BMI                0
heartRate          0
glucose            0
TenYearCHD         0
dtype: int64

In [16]:
y=data["TenYearCHD"]

In [18]:
(y==0).sum()


np.int64(3099)

In [20]:
(y==1).sum()

np.int64(557)

In [23]:
x=data.drop("TenYearCHD",axis=1)

In [25]:
x.corrwith(y)

male               0.091745
age                0.233810
education         -0.063068
currentSmoker      0.019176
cigsPerDay         0.052159
BPMeds             0.089116
prevalentStroke    0.048351
prevalentHyp       0.181556
diabetes           0.093397
totChol            0.091127
sysBP              0.222885
diaBP              0.150342
BMI                0.081931
heartRate          0.020523
glucose            0.121942
dtype: float64

In [27]:
x.drop("education",axis=1,inplace=True)

In [29]:
x.corrwith(y)

male               0.091745
age                0.233810
currentSmoker      0.019176
cigsPerDay         0.052159
BPMeds             0.089116
prevalentStroke    0.048351
prevalentHyp       0.181556
diabetes           0.093397
totChol            0.091127
sysBP              0.222885
diaBP              0.150342
BMI                0.081931
heartRate          0.020523
glucose            0.121942
dtype: float64

In [32]:
from sklearn.model_selection import train_test_split,StratifiedShuffleSplit
from sklearn.linear_model import LogisticRegression,SGDClassifier
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.metrics import confusion_matrix,precision_score,recall_score,classification_report,accuracy_score

In [33]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42,stratify=y)

In [35]:
model=LogisticRegression(max_iter=100)

In [36]:
model.fit(x_train,y_train)

E:\anaconda\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [37]:
prediction=model.predict(x_test)

In [38]:
(prediction==y_test).sum()/len(y) *100

np.float64(16.95842450765864)

In [39]:
print(classification_report(y_test,model.predict(x_test)))

              precision    recall  f1-score   support

           0       0.85      0.99      0.92       620
           1       0.50      0.05      0.10       112

    accuracy                           0.85       732
   macro avg       0.68      0.52      0.51       732
weighted avg       0.80      0.85      0.79       732



In [46]:
model.fit(x,y)

E:\anaconda\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [49]:
predict1=model.predict(x)

In [51]:
(predict1==y).sum()/len(y) *100

np.float64(85.0382932166302)

In [55]:
splitter=StratifiedShuffleSplit(n_splits=1,test_size=0.2,random_state=123)
for train_index,test_index in splitter.split(x,y):
    x_train=x.iloc[train_index]
    x_test=x.iloc[test_index]
    y_train=y.iloc[train_index]
    y_test=y.iloc[test_index]


In [57]:
model=LogisticRegression()

In [59]:
model.fit(x_train,y_train)

E:\anaconda\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [61]:
probability=model.predict(x_test)

In [63]:
(y_test==probability).sum()/len(y) *100

np.float64(16.95842450765864)

In [65]:
print(accuracy_score(y_test,probability))

0.8469945355191257


In [67]:
print(classification_report(y_test,probability))

              precision    recall  f1-score   support

           0       0.85      1.00      0.92       620
           1       0.50      0.03      0.05       112

    accuracy                           0.85       732
   macro avg       0.67      0.51      0.48       732
weighted avg       0.80      0.85      0.78       732



In [70]:
print(confusion_matrix(y_test,probability))

[[617   3]
 [109   3]]


In [74]:
log=LogisticRegression()
log.fit(x_train,y_train)
y_hat_train=log.predict(x_train)
y_hat_test=log.predict(x_test)
training_accuracy=accuracy_score(y_hat_train,y_train)
testing_accuracy=accuracy_score(y_hat_test,y_test)
print("Logstic model")
print(f"Training Accuracy : {training_accuracy}")
print(f"Testing Accuracy : {testing_accuracy}")
print(f"Training Confusion matrix :\n {confusion_matrix(y_hat_train,y_train)}")
print(f"Testing Confusion matrix :\n {confusion_matrix(y_hat_test,y_test)}")
print(f"Training classification report :\n {classification_report(y_hat_train,y_train)}")
print(f"Testing Classfication report:\n {classification_report(y_hat_test,y_test)}")

Logstic model
Training Accuracy : 0.8498632010943913
Testing Accuracy : 0.8469945355191257
Training Confusion matrix :
 [[2469  429]
 [  10   16]]
Testing Confusion matrix :
 [[617 109]
 [  3   3]]
Training classification report :
               precision    recall  f1-score   support

           0       1.00      0.85      0.92      2898
           1       0.04      0.62      0.07        26

    accuracy                           0.85      2924
   macro avg       0.52      0.73      0.49      2924
weighted avg       0.99      0.85      0.91      2924

Testing Classfication report:
               precision    recall  f1-score   support

           0       1.00      0.85      0.92       726
           1       0.03      0.50      0.05         6

    accuracy                           0.85       732
   macro avg       0.51      0.67      0.48       732
weighted avg       0.99      0.85      0.91       732



E:\anaconda\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [78]:
from sklearn.linear_model import SGDClassifier
from sklearn.svm import SVC

In [96]:
model1=SGDClassifier(loss='log_loss',max_iter=1000,verbose=3)
model2=SVC(kernel="linear")

In [98]:
model1.fit(x_train,y_train)
y_hat_train=log.predict(x_train)
y_hat_test=log.predict(x_test)
training_accuracy=accuracy_score(y_hat_train,y_train)
testing_accuracy=accuracy_score(y_hat_test,y_test)
print(" SGD Classifier")
print(f"Training Accuracy : {training_accuracy}")
print(f"Testing Accuracy : {testing_accuracy}")
print(f"Training Confusion matrix :\n {confusion_matrix(y_hat_train,y_train)}")
print(f"Testing Confusion matrix :\n {confusion_matrix(y_hat_test,y_test)}")
print(f"Training classification report :\n {classification_report(y_hat_train,y_train)}")
print(f"Testing Classfication report:\n {classification_report(y_hat_test,y_test)}")

-- Epoch 1
Norm: 3367.59, NNZs: 14, Bias: -123.749924, T: 2924, Avg. loss: 62406.120235
Total training time: 0.00 seconds.
-- Epoch 2
Norm: 2864.44, NNZs: 14, Bias: -162.096832, T: 5848, Avg. loss: 23986.679516
Total training time: 0.00 seconds.
-- Epoch 3
Norm: 2168.98, NNZs: 14, Bias: -181.528018, T: 8772, Avg. loss: 15871.328629
Total training time: 0.00 seconds.
-- Epoch 4
Norm: 1478.07, NNZs: 14, Bias: -197.070080, T: 11696, Avg. loss: 11650.182552
Total training time: 0.00 seconds.
-- Epoch 5
Norm: 1306.12, NNZs: 14, Bias: -208.191125, T: 14620, Avg. loss: 9053.517083
Total training time: 0.00 seconds.
-- Epoch 6
Norm: 1129.57, NNZs: 14, Bias: -220.095022, T: 17544, Avg. loss: 7802.802015
Total training time: 0.00 seconds.
-- Epoch 7
Norm: 1160.58, NNZs: 14, Bias: -228.515432, T: 20468, Avg. loss: 6136.631524
Total training time: 0.00 seconds.
-- Epoch 8
Norm: 1114.74, NNZs: 14, Bias: -236.383964, T: 23392, Avg. loss: 5654.512713
Total training time: 0.00 seconds.
-- Epoch 9
Norm

In [90]:
model2.fit(x_train,y_train)
y_hat_train=log.predict(x_train)
y_hat_test=log.predict(x_test)
training_accuracy=accuracy_score(y_hat_train,y_train)
testing_accuracy=accuracy_score(y_hat_test,y_test)
print(" SVM classifier")
print(f"Training Accuracy : {training_accuracy}")
print(f"Testing Accuracy : {testing_accuracy}")
print(f"Training Confusion matrix :\n {confusion_matrix(y_hat_train,y_train)}")
print(f"Testing Confusion matrix :\n {confusion_matrix(y_hat_test,y_test)}")
print(f"Training classification report :\n {classification_report(y_hat_train,y_train)}")
print(f"Testing Classfication report:\n {classification_report(y_hat_test,y_test)}")

 SVM classifier
Training Accuracy : 0.8498632010943913
Testing Accuracy : 0.8469945355191257
Training Confusion matrix :
 [[2469  429]
 [  10   16]]
Testing Confusion matrix :
 [[617 109]
 [  3   3]]
Training classification report :
               precision    recall  f1-score   support

           0       1.00      0.85      0.92      2898
           1       0.04      0.62      0.07        26

    accuracy                           0.85      2924
   macro avg       0.52      0.73      0.49      2924
weighted avg       0.99      0.85      0.91      2924

Testing Classfication report:
               precision    recall  f1-score   support

           0       1.00      0.85      0.92       726
           1       0.03      0.50      0.05         6

    accuracy                           0.85       732
   macro avg       0.51      0.67      0.48       732
weighted avg       0.99      0.85      0.91       732

